spring.application.name=java-lexical-website
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
app.elasticsearch.base-url=http://localhost:9200
app.elasticsearch.index-name=lex_text_files
app.elasticsearch.snippet-length=200
app.search.page-size=10
app.search.max-visible-pages=10
spring.devtools.restart.enabled=true